name: Build NixOS WSL2 Tarballs

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - arch: x86_64
            runs-on: ubuntu-latest
          - arch: aarch64
            runs-on: ubuntu-latest-arm64

    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Enable Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build WSL2 Tarball
        run: |
          nix build .#nixosConfigurations.wsl-${{ matrix.arch }}.config.system.build.tarballBuilder \
            --extra-experimental-features nix-command \
            --extra-experimental-features flakes \
            --out-link result-${{ matrix.arch }} \
          && sudo ./result-${{ matrix.arch }}/bin/nixos-wsl-tarball-builder

      - name: Upload Tarball
        uses: actions/upload-artifact@v3
        with:
          name: nixos-wsl-${{ matrix.arch }}
          path: nixos-wsl-${{ matrix.arch }}.tar.gz

